name: Test openfe doc building

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 7 * * 0"
  workflow_dispatch:


concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true


defaults:
  run:
    shell: bash -leo pipefail {0}


jobs:
  build_tests:
    if: "github.repository == 'OpenFreeEnergy/ofe-sphinx-theme'"
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.12"

    steps:

      - name: Checkout ofe-sphinx-theme
        uses: actions/checkout@v4
        with:
          path: ofe

      - name: Checkout openfe
        uses: actions/checkout@v4
        with:
          repository: OpenFreeEnergy/openfe
          path: openfe

      - name: Install OpenFE Doc Env
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ofe/docs/environment.yml
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Debug paths
        run: |
          ls -l ofe
          ls -l openfe
          ls -l 

      - name: Install ofe-sphinx-theme
        run: python -m pip install -e ofe/

      - name: Install openfe
        run: python -m pip install --no-deps openfe/

      - name: Build the docs
        run:  python -m sphinx -T -W --keep-going -b html -d _build/doctrees -D language=en openfe/docs/ build_output/html 
